// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace RiftGameplayTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Attacking);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dodging);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Action_Cancelable);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Staggered);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Invincible);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Blocking);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Attack_RapidSlash);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Attack_RapidSlashReady);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Intro);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Enemy_Intro);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Enemy_HitRetreat);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Enemy_SuperArmor);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_SuperArmor_Red);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Hit_Light);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Hit_Heavy);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_Primary);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_Secondary);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_Combo);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_TwinSwordCombo);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_TwinSwordRapidSlash);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Skill_TwinSword_Q);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Skill_TwinSword_SwordWave);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Enemy_MeleeAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Enemy_ShieldBlock);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Dodge);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Guard);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack_Primary);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack_Secondary);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Dodge);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Guard);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Skill_Q);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Skill_E);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Damage);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_PoiseDamage);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_UltimateCharge);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Combat_MeleeHit);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Combat_BlockedHit);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Combat_PlayerHit);
}
